[tool.poetry]
name = "miblog"
version = "0.1.0"
description = "Personal blog"
authors = ["Juan Rey <juan.rey@tuta.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
